### PR TITLE
Typechecker Implementation

### PR DESCRIPTION
**Pull request by Codysseus**
This is the initial TypeChecker implementation started in March of last year. This is unfinished in two ways: The TypeChecker is not implemented, and the rules for typechecking are not completely defined. This has two to-dos:

- [ ] Define all type checks formally
- [ ] Implement all type checks

### CODE REVIEW

**Comment by Codysseus** [comment]
Regarding the typecheck for the For expression, I am 100% behind implementing it as a do-while. Then we won't have to do something like what I was going to suggest which was either to error when the user attempts to capture the value of the for loop, or have it simply return an Opaque type that the user can't use.

Let's follow the KISS methodology ;)

**Comment by Codysseus** [comment]
We should separate tuples and vectors, vectors are homogenous and tuples are heterogenous. The Syntax and TypeChecker should refect this.

**Comment by Codysseus** [comment]
Other thoughts:
We wanted to abstract away the difference between tuples and vectors so that it optimizes in the backend. If users want to constrain the type of their tuples they can add a type annotation.

**Comment by montymxb** [comment]
Working on this a bit today.

**Comment by montymxb** [comment]
Got the typechecker to work for function application.
Would vote to take this PR as setting up the typechecking only, and instead focusing on individual TC issues as separate (or grouped) PRs as needed. If we go this route, we can immediately start work on the compiler to GLSL.

**Pull request merged**
